name: flutter_streams_lab
description: A new Flutter project to demonstrate streams and Riverpod

# Add the environment section specifying Dart SDK compatibility
environment:
  sdk: ">=3.5.0 <4.0.0"  # Adjust the version based on your Flutter version

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  # Add other dependencies as needed

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
