name: flutter_streams_lab
description: A Flutter project implementing streams for bookmarks and grocery lists.

publish_to: 'none' # Remove this line if you plan to publish the package

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/  